// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using repositorypattern.Context;

namespace NetCoreRepositoryPattern.Migrations
{
    [DbContext(typeof(EventContext))]
    [Migration("20191208005244_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("repositorypattern.Models.Comedian", b =>
                {
                    b.Property<int>("ComedianId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactPhone");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("ComedianId");

                    b.ToTable("Comedians");

                    b.HasData(
                        new
                        {
                            ComedianId = 1,
                            ContactPhone = "12312312",
                            FirstName = "Test",
                            LastName = "Test"
                        },
                        new
                        {
                            ComedianId = 2,
                            ContactPhone = "12312312",
                            FirstName = "Test",
                            LastName = "Test"
                        });
                });

            modelBuilder.Entity("repositorypattern.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EventDate");

                    b.Property<string>("EventName");

                    b.Property<int?>("VenueId");

                    b.HasKey("EventId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            EventDate = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Test"
                        });
                });

            modelBuilder.Entity("repositorypattern.Models.Gig", b =>
                {
                    b.Property<int>("GigId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ComedianId");

                    b.Property<int?>("EventId");

                    b.Property<string>("GigHeadline");

                    b.Property<int>("GigLengthInMinutes");

                    b.HasKey("GigId");

                    b.HasIndex("ComedianId");

                    b.HasIndex("EventId");

                    b.ToTable("Gigs");

                    b.HasData(
                        new
                        {
                            GigId = 1,
                            ComedianId = 1,
                            EventId = 1,
                            GigHeadline = "test",
                            GigLengthInMinutes = 60
                        },
                        new
                        {
                            GigId = 2,
                            ComedianId = 2,
                            EventId = 1,
                            GigHeadline = "test2",
                            GigLengthInMinutes = 45
                        });
                });

            modelBuilder.Entity("repositorypattern.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<int>("Seating");

                    b.Property<bool>("ServesAlcohol");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("VenueName");

                    b.Property<string>("ZipeCode");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("repositorypattern.Models.Event", b =>
                {
                    b.HasOne("repositorypattern.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId");
                });

            modelBuilder.Entity("repositorypattern.Models.Gig", b =>
                {
                    b.HasOne("repositorypattern.Models.Comedian", "Comedian")
                        .WithMany()
                        .HasForeignKey("ComedianId");

                    b.HasOne("repositorypattern.Models.Event", "Event")
                        .WithMany("Gigs")
                        .HasForeignKey("EventId");
                });
#pragma warning restore 612, 618
        }
    }
}
